clc;clear all;close all;
Fs=10000;
fn=Fs/2;
delp=10^(0.01/20)-1;
dels=10^(-60/20);
fc=[850 2150];
mag=[0 1 0];
dev=[dels delp dels];
[N,wn,beta,ftype]=kaiserord(fc,mag,dev,Fs);
hn=fir1(N-1,wn,kaiser(N,beta));
[H,f]=freqz(hn,1,512,Fs);
mag=20*log10(abs(H));
plot(f,mag),grid on;
xlabel('frequency(hz)');
ylabel('magnitude response(db)');
title('frequency response of BPF using kaiser window');
n=0:N-1;
figure;
stem(n,hn);