clc;clear all;close all;
x=input('type in a N point sequence which is a power of 2');
N=length(x);
X=fft(x,N);
magX=abs(X);
phaX=angle(X);
n=0:N-1;
subplot(3,1,1);
stem(n,x);
title('time domain sequence');
xlabel('time index n');
ylabel('magnitude');
subplot(3,1,2);
k=0:N-1;
stem(k,magX);
title('magnitude of the dft samples');
xlabel('frequency index k');
ylabel('magnitude');
subplot(3,1,3);
stem(k,phaX);
title('phase of dft samples');
xlabel('frequency index k');
ylabel('phase(radians)');
disp('input sequence');
disp(x);
disp('dft of the sequence');
disp(X);
x1=ifft(X,N);
disp(x1)